"""gamified challenges

Revision ID: 1eb569cbd764
Revises: 
Create Date: 2026-07-03 16:14:54.923457
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb569cbd764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('LIMIT', 'TARGET', 'STREAK', name='challengetype'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='challengestatus'), nullable=False),
    sa.Column('current_progress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_profiles', sa.Column('streak_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_profiles', sa.Column('last_logged_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('total_points', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'total_points')
    op.drop_column('user_profiles', 'last_logged_date')
    op.drop_column('user_profiles', 'streak_days')
    op.drop_table('user_challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
