"""Add target weight

Revision ID: 3da8ed8e033b
Revises: 1eb569cbd764
Create Date: 2026-07-06 18:39:27.780187
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da8ed8e033b'
down_revision: Union[str, None] = '1eb569cbd764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('target_weight_kg', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('target_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'target_date')
    op.drop_column('user_profiles', 'target_weight_kg')
    # ### end Alembic commands ###
